### ISSUE TITLE
Remove `nocheck` option

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/stata-linter#24] opened 2021-12-13 23:18 UTC
Remove the option `nocheck`. It's described as follows in the current (v0.04) version:

>     nocheck                    Do not show suggestions to check and only show style problems

**Comment by luisesanmartin** [comment] 2021-12-13 23:26
Note that this should also be removed in the help file

**Comment by luizaandrade** [comment] 2022-01-04 12:30
#26 is still not working for me, and I believe the issue is still related to #30

**Comment by luizaandrade** [comment] 2022-01-04 13:09
resolved by #26

**Comment by luisesanmartin** [comment] 2022-01-11 19:00
@luizaandrade can we close this issue now or should we wait until #32 is merged into `main`?

**Closed** 2022-12-06 15:42 UTC
Labels: v1.0
